In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("Libraries imported successfully!")

Libraries imported successfully!

In [8]:
import os

print("Current folder:")
print(os.getcwd())

print("\nFiles/folders here:")
print(os.listdir())

Current folder:
D:\AI_Disaster_Prediction_Blockchain_Fund_Allocation\AI_Disaster_Prediction_Blockchain_Fund_Allocation\ml_training\flood

Files/folders here:
['.ipynb_checkpoints', 'data', 'flood_model_training.ipynb', 'models', 'notebooks', 'predictions', 'results', 'src', 'Untitled.ipynb']

In [9]:
data = pd.read_csv("data/raw/flood.csv")

print("Dataset shape:", data.shape)
print("Columns:")
print(data.columns.tolist())
print("\nFirst 5 rows:")
print(data.head())

Dataset shape: (50000, 21)
Columns:
['MonsoonIntensity', 'TopographyDrainage', 'RiverManagement', 'Deforestation', 'Urbanization', 'ClimateChange', 'DamsQuality', 'Siltation', 'AgriculturalPractices', 'Encroachments', 'IneffectiveDisasterPreparedness', 'DrainageSystems', 'CoastalVulnerability', 'Landslides', 'Watersheds', 'DeterioratingInfrastructure', 'PopulationScore', 'WetlandLoss', 'InadequatePlanning', 'PoliticalFactors', 'FloodProbability']

First 5 rows:
   MonsoonIntensity  TopographyDrainage  RiverManagement  Deforestation  \
0                 3                   8                6              6
1                 8                   4                5              7
2                 3                  10                4              1
3                 4                   4                2              7
4                 3                   7                5              2

   Urbanization  ClimateChange  DamsQuality  Siltation  AgriculturalPractices  \
0             4              4            6          2                      3
1             7              9            1          5                      5
2             7              5            4          7                      4
3             3              4            1          4                      6
4             5              8            5          2                      7

   Encroachments  ...  DrainageSystems  CoastalVulnerability  Landslides  \
0              2  ...               10                     7           4
1              4  ...                9                     2           6
2              9  ...                7                     4           4
3              4  ...                4                     2           6
4              5  ...                7                     6           5

   Watersheds  DeterioratingInfrastructure  PopulationScore  WetlandLoss  \
0           2                            3                4            3
1           2                            1                1            9
2           8                            6                1            8
3           6                            8                8            6
4           3                            3                4            4

   InadequatePlanning  PoliticalFactors  FloodProbability
0                   2                 6             0.450
1                   1                 3             0.475
2                   3                 6             0.515
3                   6                10             0.520
4                   3                 4             0.475

[5 rows x 21 columns]

In [10]:
print("Target column:", "FloodProbability")

print("\nTarget statistics:")
print(data["FloodProbability"].describe())

print("\nMissing values:")
print(data.isnull().sum().sum())

print("\nData types:")
print(data.dtypes)

Target column: FloodProbability

Target statistics:
count    50000.000000
mean         0.499660
std          0.050034
min          0.285000
25%          0.465000
50%          0.500000
75%          0.535000
max          0.725000
Name: FloodProbability, dtype: float64

Missing values:
0

Data types:
MonsoonIntensity                     int64
TopographyDrainage                   int64
RiverManagement                      int64
Deforestation                        int64
Urbanization                         int64
ClimateChange                        int64
DamsQuality                          int64
Siltation                            int64
AgriculturalPractices                int64
Encroachments                        int64
IneffectiveDisasterPreparedness      int64
DrainageSystems                      int64
CoastalVulnerability                 int64
Landslides                           int64
Watersheds                           int64
DeterioratingInfrastructure          int64
PopulationScore                      int64
WetlandLoss                          int64
InadequatePlanning                   int64
PoliticalFactors                     int64
FloodProbability                   float64
dtype: object

In [11]:
# Separate features and target

X = data.drop(columns=["FloodProbability"])
y = data["FloodProbability"]

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

print("\nFeatures:")
print(X.columns.tolist())

Feature shape: (50000, 20)
Target shape: (50000,)

Features:
['MonsoonIntensity', 'TopographyDrainage', 'RiverManagement', 'Deforestation', 'Urbanization', 'ClimateChange', 'DamsQuality', 'Siltation', 'AgriculturalPractices', 'Encroachments', 'IneffectiveDisasterPreparedness', 'DrainageSystems', 'CoastalVulnerability', 'Landslides', 'Watersheds', 'DeterioratingInfrastructure', 'PopulationScore', 'WetlandLoss', 'InadequatePlanning', 'PoliticalFactors']

In [12]:
# Split dataset into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)
print("Training target shape:", y_train.shape)
print("Testing target shape:", y_test.shape)

Training data shape: (40000, 20)
Testing data shape: (10000, 20)
Training target shape: (40000,)
Testing target shape: (10000,)

X_train_scaled shape: (40000, 20)
X_test_scaled shape: (10000, 20)

In [14]:
# Reshape data for LSTM

X_train_lstm = X_train_scaled.reshape(
    X_train_scaled.shape[0],
    X_train_scaled.shape[1],
    1
)

X_test_lstm = X_test_scaled.reshape(
    X_test_scaled.shape[0],
    X_test_scaled.shape[1],
    1
)

print("LSTM training shape:", X_train_lstm.shape)
print("LSTM testing shape:", X_test_lstm.shape)

LSTM training shape: (40000, 20, 1)
LSTM testing shape: (10000, 20, 1)

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

print("Building Baseline LSTM model...")

model = Sequential([
    LSTM(64, input_shape=(20, 1)),
    Dropout(0.2),
    Dense(32, activation="relu"),
    Dense(1, activation="linear")
])

model.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae"]
)

model.summary()

Building Baseline LSTM model...

D:\AI_Disaster_Prediction_Blockchain_Fund_Allocation\AI_Disaster_Prediction_Blockchain_Fund_Allocation\ml_training\venv-ml\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                          │ (None, 64)                  │          16,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 19,009 (74.25 KB)

 Trainable params: 19,009 (74.25 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
print("Starting LSTM training...")

history = model.fit(
    X_train_lstm,
    y_train,
    validation_split=0.2,
    epochs=20,
    batch_size=64,
    verbose=1
)

print("LSTM training completed!")

Starting LSTM training...
Epoch 1/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 0.0049 - mae: 0.0386 - val_loss: 5.8755e-05 - val_mae: 0.0062
Epoch 2/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 3.0039e-04 - mae: 0.0135 - val_loss: 1.2795e-04 - val_mae: 0.0106
Epoch 3/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 8.7272e-05 - mae: 0.0071 - val_loss: 7.5509e-06 - val_mae: 0.0022
Epoch 4/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 4.2382e-05 - mae: 0.0049 - val_loss: 9.1301e-06 - val_mae: 0.0024
Epoch 5/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 3.2129e-05 - mae: 0.0043 - val_loss: 1.4585e-05 - val_mae: 0.0034
Epoch 6/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 2.7432e-05 - mae: 0.0039 - val_loss: 6.0959e-06 - val_mae: 0.0019
Epoch 7/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 2.7130e-05 - mae: 0.0039 - val_loss: 8.8331e-06 - val_mae: 0.0025
Epoch 8/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 2.5895e-05 - mae: 0.0038 - val_loss: 6.2917e-06 - val_mae: 0.0019
Epoch 9/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 2.4297e-05 - mae: 0.0037 - val_loss: 9.2422e-06 - val_mae: 0.0025
Epoch 10/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 2.2727e-05 - mae: 0.0036 - val_loss: 9.4061e-06 - val_mae: 0.0025
Epoch 11/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 2.2908e-05 - mae: 0.0036 - val_loss: 1.0535e-05 - val_mae: 0.0027
Epoch 12/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 2.0468e-05 - mae: 0.0034 - val_loss: 7.5674e-06 - val_mae: 0.0022
Epoch 13/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 1.9726e-05 - mae: 0.0034 - val_loss: 3.9939e-06 - val_mae: 0.0015
Epoch 14/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 1.9416e-05 - mae: 0.0033 - val_loss: 1.2637e-05 - val_mae: 0.0030
Epoch 15/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 1.8530e-05 - mae: 0.0032 - val_loss: 2.3542e-05 - val_mae: 0.0043
Epoch 16/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 1.7947e-05 - mae: 0.0032 - val_loss: 9.6939e-06 - val_mae: 0.0027
Epoch 17/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 1.6938e-05 - mae: 0.0031 - val_loss: 4.6587e-06 - val_mae: 0.0017
Epoch 18/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 1.7257e-05 - mae: 0.0031 - val_loss: 3.8969e-06 - val_mae: 0.0015
Epoch 19/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 1.7231e-05 - mae: 0.0031 - val_loss: 9.5070e-06 - val_mae: 0.0025
Epoch 20/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 1.6661e-05 - mae: 0.0031 - val_loss: 1.6648e-05 - val_mae: 0.0037
LSTM training completed!

In [17]:
print("Evaluating Baseline LSTM...")

y_pred_lstm = model.predict(X_test_lstm).flatten()

mae_lstm = mean_absolute_error(y_test, y_pred_lstm)
rmse_lstm = np.sqrt(mean_squared_error(y_test, y_pred_lstm))
r2_lstm = r2_score(y_test, y_pred_lstm)

print("\nBaseline LSTM Results")
print("--------------------")
print(f"MAE  : {mae_lstm:.6f}")
print(f"RMSE : {rmse_lstm:.6f}")
print(f"R²   : {r2_lstm:.6f}")

Evaluating Baseline LSTM...
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

Baseline LSTM Results
--------------------
MAE  : 0.003740
RMSE : 0.004122
R²   : 0.993178

In [18]:
model.save("models/flood_baseline_lstm_notebook.keras")

print("Baseline LSTM model saved successfully!")

Baseline LSTM model saved successfully!

In [19]:
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("Training Baseline XGBoost...")

# Create XGBoost model
xgb_model = XGBRegressor(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="reg:squarederror",
    random_state=42
)

# Train
xgb_model.fit(X_train, y_train)

# Predict
xgb_predictions = xgb_model.predict(X_test)

# Evaluation
xgb_mae = mean_absolute_error(y_test, xgb_predictions)
xgb_rmse = np.sqrt(mean_squared_error(y_test, xgb_predictions))
xgb_r2 = r2_score(y_test, xgb_predictions)

print("\nBaseline XGBoost Results:")
print(f"MAE  : {xgb_mae:.6f}")
print(f"RMSE : {xgb_rmse:.6f}")
print(f"R²   : {xgb_r2:.6f}")

# Save model
xgb_model.save_model("models/flood_baseline_xgb_notebook.json")

print("\nBaseline XGBoost model saved successfully!")

Training Baseline XGBoost...

Baseline XGBoost Results:
MAE  : 0.011320
RMSE : 0.014447
R²   : 0.916196

Baseline XGBoost model saved successfully!

In [26]:
# Create LSTM train/test data correctly

X = data.drop(columns=['FloodProbability']).values
y = data['FloodProbability'].values

# Same 80/20 split used for your models
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Reshape for LSTM/CNN-LSTM
X_train_lstm = X_train.reshape(
    X_train.shape[0],
    X_train.shape[1],
    1
)

X_test_lstm = X_test.reshape(
    X_test.shape[0],
    X_test.shape[1],
    1
)

y_train_lstm = y_train
y_test_lstm = y_test

print("X_train_lstm:", X_train_lstm.shape)
print("X_test_lstm :", X_test_lstm.shape)
print("y_train_lstm:", y_train_lstm.shape)
print("y_test_lstm :", y_test_lstm.shape)

X_train_lstm: (40000, 20, 1)
X_test_lstm : (10000, 20, 1)
y_train_lstm: (40000,)
y_test_lstm : (10000,)

In [27]:
# Prepare data for LSTM / CNN-LSTM

X_train_lstm = np.array(X_train).reshape(
    X_train.shape[0],
    X_train.shape[1],
    1
)

X_test_lstm = np.array(X_test).reshape(
    X_test.shape[0],
    X_test.shape[1],
    1
)

y_train_lstm = np.array(y_train)
y_test_lstm = np.array(y_test)

print("LSTM training shape:", X_train_lstm.shape)
print("LSTM testing shape:", X_test_lstm.shape)
print("LSTM target training shape:", y_train_lstm.shape)
print("LSTM target testing shape:", y_test_lstm.shape)

LSTM training shape: (40000, 20, 1)
LSTM testing shape: (10000, 20, 1)
LSTM target training shape: (40000,)
LSTM target testing shape: (10000,)

In [28]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, LSTM, Dense, Dropout

print("Building CNN-LSTM model...")

cnn_lstm_model = Sequential([
    Conv1D(
        filters=64,
        kernel_size=3,
        activation='relu',
        input_shape=(X_train_lstm.shape[1], X_train_lstm.shape[2])
    ),

    MaxPooling1D(pool_size=2),

    LSTM(64),

    Dropout(0.2),

    Dense(32, activation='relu'),

    Dense(1)
])

cnn_lstm_model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

cnn_lstm_model.summary()

Building CNN-LSTM model...

D:\AI_Disaster_Prediction_Blockchain_Fund_Allocation\AI_Disaster_Prediction_Blockchain_Fund_Allocation\ml_training\venv-ml\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv1d_1 (Conv1D)                    │ (None, 18, 64)              │             256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling1d_1 (MaxPooling1D)       │ (None, 9, 64)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_2 (LSTM)                        │ (None, 64)                  │          33,024 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 35,393 (138.25 KB)

 Trainable params: 35,393 (138.25 KB)

 Non-trainable params: 0 (0.00 B)

In [29]:
print("Training CNN-LSTM...")

history_cnn_lstm = cnn_lstm_model.fit(
    X_train_lstm,
    y_train_lstm,
    epochs=20,
    batch_size=64,
    validation_split=0.2,
    verbose=1
)

print("CNN-LSTM training completed!")

Training CNN-LSTM...
Epoch 1/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 0.0045 - mae: 0.0429 - val_loss: 6.1972e-04 - val_mae: 0.0215
Epoch 2/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 5.9246e-04 - mae: 0.0189 - val_loss: 0.0023 - val_mae: 0.0464
Epoch 3/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 3.2164e-04 - mae: 0.0138 - val_loss: 0.0019 - val_mae: 0.0429
Epoch 4/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 1.6492e-04 - mae: 0.0097 - val_loss: 9.1467e-04 - val_mae: 0.0289
Epoch 5/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 1.0975e-04 - mae: 0.0081 - val_loss: 0.0016 - val_mae: 0.0383
Epoch 6/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 7.7310e-05 - mae: 0.0067 - val_loss: 0.0012 - val_mae: 0.0332
Epoch 7/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 6.8941e-05 - mae: 0.0064 - val_loss: 8.5080e-04 - val_mae: 0.0280
Epoch 8/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 5.2143e-05 - mae: 0.0055 - val_loss: 0.0011 - val_mae: 0.0315
Epoch 9/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 4.8231e-05 - mae: 0.0053 - val_loss: 8.0727e-04 - val_mae: 0.0271
Epoch 10/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 3.6634e-05 - mae: 0.0046 - val_loss: 6.2803e-04 - val_mae: 0.0240
Epoch 11/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 3.7984e-05 - mae: 0.0047 - val_loss: 6.9652e-04 - val_mae: 0.0251
Epoch 12/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 3.4428e-05 - mae: 0.0044 - val_loss: 6.2674e-04 - val_mae: 0.0234
Epoch 13/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 2.6189e-05 - mae: 0.0039 - val_loss: 5.9796e-04 - val_mae: 0.0231
Epoch 14/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 2.6654e-05 - mae: 0.0039 - val_loss: 6.7116e-04 - val_mae: 0.0242
Epoch 15/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 2.6564e-05 - mae: 0.0040 - val_loss: 7.4142e-04 - val_mae: 0.0256
Epoch 16/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 2.1724e-05 - mae: 0.0036 - val_loss: 7.1934e-04 - val_mae: 0.0253
Epoch 17/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 2.0772e-05 - mae: 0.0035 - val_loss: 0.0014 - val_mae: 0.0364
Epoch 18/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 1.9251e-05 - mae: 0.0033 - val_loss: 8.3216e-04 - val_mae: 0.0269
Epoch 19/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 1.7399e-05 - mae: 0.0031 - val_loss: 7.7081e-04 - val_mae: 0.0262
Epoch 20/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 1.7639e-05 - mae: 0.0032 - val_loss: 7.8848e-04 - val_mae: 0.0265
CNN-LSTM training completed!

In [30]:
print("Evaluating CNN-LSTM...")

cnn_lstm_predictions = cnn_lstm_model.predict(
    X_test_lstm,
    verbose=0
).flatten()

print("Predictions generated!")
print("Prediction shape:", cnn_lstm_predictions.shape)

Evaluating CNN-LSTM...
Predictions generated!
Prediction shape: (10000,)

In [31]:
mae_cnn_lstm = mean_absolute_error(
    y_test_lstm,
    cnn_lstm_predictions
)

rmse_cnn_lstm = np.sqrt(
    mean_squared_error(
        y_test_lstm,
        cnn_lstm_predictions
    )
)

r2_cnn_lstm = r2_score(
    y_test_lstm,
    cnn_lstm_predictions
)

print("CNN-LSTM Results:")
print(f"MAE  : {mae_cnn_lstm:.6f}")
print(f"RMSE : {rmse_cnn_lstm:.6f}")
print(f"R²   : {r2_cnn_lstm:.6f}")

CNN-LSTM Results:
MAE  : 0.026525
RMSE : 0.028078
R²   : 0.683458

In [32]:
cnn_lstm_model.save("models/flood_cnn_lstm.keras")

print("CNN-LSTM model saved successfully!")

CNN-LSTM model saved successfully!

In [34]:
import pandas as pd

comparison = pd.DataFrame({
    "Model": [
        "Baseline LSTM",
        "Baseline XGBoost",
        "CNN-LSTM"
    ],
    "MAE": [
        mae_lstm,
        0.011320,
        mae_cnn_lstm
    ],
    "RMSE": [
        rmse_lstm,
        0.014447,
        rmse_cnn_lstm
    ],
    "R2": [
        r2_lstm,
        0.916196,
        r2_cnn_lstm
    ]
})

print("Model Comparison:")
display(comparison)

Model Comparison:

              Model       MAE      RMSE        R2
0     Baseline LSTM  0.003740  0.004122  0.993178
1  Baseline XGBoost  0.011320  0.014447  0.916196
2          CNN-LSTM  0.026525  0.028078  0.683458

In [35]:
comparison.to_csv("results/model_comparison.csv", index=False)

print("Model comparison saved successfully!")

Model comparison saved successfully!

In [38]:
import os

print(os.listdir("models"))

['flood_baseline_lstm_notebook.keras', 'flood_baseline_xgb_notebook.json', 'flood_cnn_lstm.keras']

In [39]:
import tensorflow as tf

print("Loading saved LSTM model...")

lstm_model = tf.keras.models.load_model(
    "models/flood_baseline_lstm_notebook.keras"
)

print("LSTM model loaded successfully!")

Loading saved LSTM model...
LSTM model loaded successfully!

In [40]:
print("Generating LSTM predictions...")

lstm_predictions = lstm_model.predict(
    X_test_lstm,
    verbose=0
).flatten()

print("LSTM predictions generated!")
print("Prediction shape:", lstm_predictions.shape)
print("First 10 predictions:")
print(lstm_predictions[:10])

Generating LSTM predictions...
LSTM predictions generated!
Prediction shape: (10000,)
First 10 predictions:
[3.1002705 3.0943315 3.11772   3.0790892 3.0977225 3.1250067 3.1417894
 3.118257  3.1441357 3.1646035]

In [41]:
print("X_test_lstm first values:")
print(X_test_lstm[0][:10])

print("\nX_test_lstm min:", X_test_lstm.min())
print("X_test_lstm max:", X_test_lstm.max())

print("\nExpected target range:")
print("Minimum:", y_test_lstm.min())
print("Maximum:", y_test_lstm.max())

X_test_lstm first values:
[[7]
 [3]
 [4]
 [4]
 [5]
 [6]
 [2]
 [5]
 [5]
 [4]]

X_test_lstm min: 0
X_test_lstm max: 22

Expected target range:
Minimum: 0.315
Maximum: 0.705

In [42]:
import joblib
import numpy as np

print("Loading flood scaler...")

scaler = joblib.load("data/processed/flood_scaler.pkl")

print("Scaler loaded successfully!")

Loading flood scaler...
Scaler loaded successfully!

In [44]:
# Get the 20 feature columns
feature_columns = [
    col for col in data.columns
    if col != "FloodProbability"
]

# Take the test data as a DataFrame
X_test_df = data[feature_columns].iloc[-len(X_test_lstm):].copy()

# Scale using the saved scaler
X_test_scaled_2d = scaler.transform(X_test_df)

# Convert to LSTM shape
X_test_scaled = X_test_scaled_2d.reshape(
    X_test_scaled_2d.shape[0],
    X_test_scaled_2d.shape[1],
    1
)

print("Scaled test shape:", X_test_scaled.shape)
print("Scaled min:", X_test_scaled.min())
print("Scaled max:", X_test_scaled.max())

Scaled test shape: (10000, 20, 1)
Scaled min: 0.0
Scaled max: 1.0

In [45]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae_lstm = mean_absolute_error(y_test_lstm, lstm_predictions)
rmse_lstm = np.sqrt(mean_squared_error(y_test_lstm, lstm_predictions))
r2_lstm = r2_score(y_test_lstm, lstm_predictions)

print("Corrected LSTM Results:")
print(f"MAE  : {mae_lstm:.6f}")
print(f"RMSE : {rmse_lstm:.6f}")
print(f"R²   : {r2_lstm:.6f}")

Corrected LSTM Results:
MAE  : 2.635548
RMSE : 2.636016
R²   : -2788.937678

In [46]:
# Recreate the train/test data correctly

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# Features and target
X = data.drop(columns=["FloodProbability"])
y = data["FloodProbability"]

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

# Scale features
scaler_lstm = MinMaxScaler()

X_train_scaled = scaler_lstm.fit_transform(X_train)
X_test_scaled = scaler_lstm.transform(X_test)

# Convert to LSTM format
X_train_lstm = X_train_scaled.reshape(
    X_train_scaled.shape[0],
    X_train_scaled.shape[1],
    1
)

X_test_lstm = X_test_scaled.reshape(
    X_test_scaled.shape[0],
    X_test_scaled.shape[1],
    1
)

# Targets
y_train_lstm = y_train.to_numpy()
y_test_lstm = y_test.to_numpy()

print("X_train_lstm:", X_train_lstm.shape)
print("X_test_lstm :", X_test_lstm.shape)
print("y_train_lstm:", y_train_lstm.shape)
print("y_test_lstm :", y_test_lstm.shape)

print("\nTarget range:")
print("Train:", y_train_lstm.min(), "to", y_train_lstm.max())
print("Test :", y_test_lstm.min(), "to", y_test_lstm.max())

print("\nInput range:")
print(X_train_lstm.min(), "to", X_train_lstm.max())

X_train_lstm: (40000, 20, 1)
X_test_lstm : (10000, 20, 1)
y_train_lstm: (40000,)
y_test_lstm : (10000,)

Target range:
Train: 0.285 to 0.725
Test : 0.315 to 0.705

Input range:
0.0 to 1.0

In [47]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

print("Building LSTM model...")

lstm_model = Sequential([
    LSTM(
        64,
        input_shape=(X_train_lstm.shape[1], X_train_lstm.shape[2])
    ),
    Dropout(0.2),
    Dense(32, activation="relu"),
    Dense(1)
])

lstm_model.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae"]
)

lstm_model.summary()

Building LSTM model...

D:\AI_Disaster_Prediction_Blockchain_Fund_Allocation\AI_Disaster_Prediction_Blockchain_Fund_Allocation\ml_training\venv-ml\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm_3 (LSTM)                        │ (None, 64)                  │          16,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_3 (Dropout)                  │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 19,009 (74.25 KB)

 Trainable params: 19,009 (74.25 KB)

 Non-trainable params: 0 (0.00 B)

In [48]:
print("Training corrected LSTM...")

history_lstm = lstm_model.fit(
    X_train_lstm,
    y_train_lstm,
    epochs=20,
    batch_size=64,
    validation_split=0.2,
    verbose=1
)

print("Corrected LSTM training completed!")

Training corrected LSTM...
Epoch 1/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - loss: 0.0044 - mae: 0.0374 - val_loss: 2.8587e-04 - val_mae: 0.0158
Epoch 2/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 3.7782e-04 - mae: 0.0151 - val_loss: 1.4107e-05 - val_mae: 0.0028
Epoch 3/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 1.0195e-04 - mae: 0.0077 - val_loss: 5.7368e-06 - val_mae: 0.0019
Epoch 4/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 3.6701e-05 - mae: 0.0046 - val_loss: 9.7952e-06 - val_mae: 0.0026
Epoch 5/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 2.7818e-05 - mae: 0.0040 - val_loss: 8.1384e-06 - val_mae: 0.0024
Epoch 6/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 2.7539e-05 - mae: 0.0039 - val_loss: 1.1104e-05 - val_mae: 0.0029
Epoch 7/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 2.5557e-05 - mae: 0.0038 - val_loss: 2.6175e-05 - val_mae: 0.0048
Epoch 8/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 2.3313e-05 - mae: 0.0036 - val_loss: 5.9749e-06 - val_mae: 0.0020
Epoch 9/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 2.4863e-05 - mae: 0.0037 - val_loss: 1.1856e-05 - val_mae: 0.0030
Epoch 10/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 2.2820e-05 - mae: 0.0036 - val_loss: 1.5340e-05 - val_mae: 0.0034
Epoch 11/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 2.2633e-05 - mae: 0.0036 - val_loss: 5.7863e-06 - val_mae: 0.0020
Epoch 12/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 2.2960e-05 - mae: 0.0036 - val_loss: 4.0696e-06 - val_mae: 0.0016
Epoch 13/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 2.3021e-05 - mae: 0.0036 - val_loss: 4.3938e-06 - val_mae: 0.0016
Epoch 14/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 2.1680e-05 - mae: 0.0035 - val_loss: 3.5002e-06 - val_mae: 0.0014
Epoch 15/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 1.9835e-05 - mae: 0.0033 - val_loss: 1.4532e-05 - val_mae: 0.0032
Epoch 16/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 2.0068e-05 - mae: 0.0033 - val_loss: 5.6314e-06 - val_mae: 0.0018
Epoch 17/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 1.7159e-05 - mae: 0.0031 - val_loss: 3.0481e-06 - val_mae: 0.0014
Epoch 18/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 1.9001e-05 - mae: 0.0033 - val_loss: 7.0058e-06 - val_mae: 0.0021
Epoch 19/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 1.7009e-05 - mae: 0.0031 - val_loss: 3.1431e-06 - val_mae: 0.0014
Epoch 20/20
500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 1.6158e-05 - mae: 0.0030 - val_loss: 6.6020e-06 - val_mae: 0.0021
Corrected LSTM training completed!

In [50]:
print("Available models:")
print([name for name in globals() if "model" in name.lower()])

Available models:
['model', 'xgb_model', 'cnn_lstm_model', 'lstm_model']

In [51]:
print("Evaluating corrected LSTM...")

corrected_lstm_predictions = lstm_model.predict(
    X_test_lstm,
    verbose=0
).flatten()

print("Corrected LSTM predictions generated!")
print("Prediction shape:", corrected_lstm_predictions.shape)
print("First 10 predictions:")
print(corrected_lstm_predictions[:10])

Evaluating corrected LSTM...
Corrected LSTM predictions generated!
Prediction shape: (10000,)
First 10 predictions:
[0.45589298 0.49093825 0.4689419  0.45818764 0.463545   0.53246325
 0.49003232 0.4789009  0.60330766 0.4882139 ]

In [52]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

print("Evaluating corrected LSTM...")

mae_corrected_lstm = mean_absolute_error(
    y_test_lstm,
    corrected_lstm_predictions
)

rmse_corrected_lstm = np.sqrt(
    mean_squared_error(
        y_test_lstm,
        corrected_lstm_predictions
    )
)

r2_corrected_lstm = r2_score(
    y_test_lstm,
    corrected_lstm_predictions
)

print("\nCorrected LSTM Results:")
print(f"MAE  : {mae_corrected_lstm:.6f}")
print(f"RMSE : {rmse_corrected_lstm:.6f}")
print(f"R²   : {r2_corrected_lstm:.6f}")

Evaluating corrected LSTM...

Corrected LSTM Results:
MAE  : 0.002053
RMSE : 0.002553
R²   : 0.997384

In [54]:
import os

os.makedirs("models", exist_ok=True)

lstm_model.save("models/flood_corrected_lstm.keras")

print("Corrected LSTM model saved successfully!")

Corrected LSTM model saved successfully!

In [55]:
import os

print(os.listdir("models"))

['flood_baseline_lstm_notebook.keras', 'flood_baseline_xgb_notebook.json', 'flood_cnn_lstm.keras', 'flood_corrected_lstm.keras']

In [56]:
import pandas as pd
import os

final_results = pd.DataFrame({
    "Model": [
        "Baseline LSTM",
        "Baseline XGBoost",
        "CNN-LSTM",
        "Corrected LSTM"
    ],
    "MAE": [
        0.003740,
        0.011320,
        0.026525,
        0.002053
    ],
    "RMSE": [
        0.004122,
        0.014447,
        0.028078,
        0.002553
    ],
    "R2": [
        0.993178,
        0.916196,
        0.683458,
        0.997384
    ]
})

print("Final Model Comparison:")
display(final_results)

os.makedirs("results", exist_ok=True)

final_results.to_csv(
    "results/final_model_comparison.csv",
    index=False
)

print("Final model comparison saved successfully!")

Final Model Comparison:

              Model       MAE      RMSE        R2
0     Baseline LSTM  0.003740  0.004122  0.993178
1  Baseline XGBoost  0.011320  0.014447  0.916196
2          CNN-LSTM  0.026525  0.028078  0.683458
3    Corrected LSTM  0.002053  0.002553  0.997384

Final model comparison saved successfully!

In [57]:
import os
import pandas as pd
import numpy as np

print("Generating final flood predictions...")

final_predictions = lstm_model.predict(
    X_test_lstm,
    verbose=0
).flatten()

print("Predictions generated!")
print("Prediction shape:", final_predictions.shape)
print("First 10 predictions:")
print(final_predictions[:10])

Generating final flood predictions...
Predictions generated!
Prediction shape: (10000,)
First 10 predictions:
[0.45589298 0.49093825 0.4689419  0.45818764 0.463545   0.53246325
 0.49003232 0.4789009  0.60330766 0.4882139 ]

In [59]:
print("Generating final flood predictions using Corrected LSTM...")

final_predictions = lstm_model.predict(
    X_test_lstm,
    verbose=0
).flatten()

print("Predictions generated!")
print("Prediction shape:", final_predictions.shape)
print("First 10 predictions:")
print(final_predictions[:10])

Generating final flood predictions using Corrected LSTM...
Predictions generated!
Prediction shape: (10000,)
First 10 predictions:
[0.45589298 0.49093825 0.4689419  0.45818764 0.463545   0.53246325
 0.49003232 0.4789009  0.60330766 0.4882139 ]

In [60]:
import pandas as pd
import os

os.makedirs("predictions", exist_ok=True)

final_predictions_df = pd.DataFrame({
    "FloodProbability": final_predictions
})

final_predictions_df.to_csv(
    "predictions/final_flood_predictions.csv",
    index=False
)

print("Final predictions saved successfully!")
print("Shape:", final_predictions_df.shape)
print(final_predictions_df.head(10))

Final predictions saved successfully!
Shape: (10000, 1)
   FloodProbability
0          0.455893
1          0.490938
2          0.468942
3          0.458188
4          0.463545
5          0.532463
6          0.490032
7          0.478901
8          0.603308
9          0.488214

In [61]:
import os

print("Checking flood ML outputs...")

print("\nModels:")
print(os.listdir("models"))

print("\nPredictions:")
print(os.listdir("predictions"))

print("\nResults:")
print(os.listdir("results"))

Checking flood ML outputs...

Models:
['flood_baseline_lstm_notebook.keras', 'flood_baseline_xgb_notebook.json', 'flood_cnn_lstm.keras', 'flood_corrected_lstm.keras']

Predictions:
['final_flood_predictions.csv']

Results:
['final_model_comparison.csv', 'model_comparison.csv']